from .wireguard_peers_ubuntu_configuration_task import WireguardPeersUbuntuConfigurationTask
from .wireguard_peers_windows_configuration_task import WireguardPeersWindowsConfigurationTask

__all__ = ["WireguardPeersUbuntuConfigurationTask", "WireguardPeersWindowsConfigurationTask"]
