from .wireguard_ubuntu_installer_task import WireguardUbuntuInstallerTask
from .wireguard_windows_installer_task import WireguardWindowsInstallerTask

__all__ = ["WireguardUbuntuInstallerTask", "WireguardWindowsInstallerTask"]