from .wireguard_share_ubuntu_configuration_task import WireguardShareUbuntuConfigurationTask
from .wireguard_share_windows_configuration_task import WireguardShareWindowsConfigurationTask

__all__ = ["WireguardShareUbuntuConfigurationTask", "WireguardShareWindowsConfigurationTask"]
