from .nginx_ubuntu_configuration_task import NginxUbuntuConfigurationTask
from .nginx_windows_configuration_task import NginxWindowsConfigurationTask

__all__ = ["NginxUbuntuConfigurationTask", "NginxWindowsConfigurationTask"]